"use client";

import React from "react";

const PDFReport = () => {
  const handleClick = async () => {
    // Import html2pdf.js dynamically inside the handler
    const html2pdf = (await import("html2pdf.js")).default;

    const element = document.querySelector('#report') as HTMLElement | null;
    if (!element) return;

    html2pdf(element, {
      margin: 20
    });
  };

  
  return (
    <div className="p-8 text-black">
      {/* Preview Section */}
      <div className="bg-[#ffff] text-[#000] rounded-xl shadow-xl p-10 max-w-4xl mx-auto" id="report">
        {/* Header */}
        <h1 className="text-3xl font-bold text-center mb-6">
          Rainwater Harvesting Insights Report
        </h1>
        <p className="text-center text-sm text-[#4a5565] mb-10">
          Generated by Smart Rainwater Management System
        </p>

        {/* Section 1: Summary */}
        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3 border-b border-[#d1d5dc] pb-2">
            📊 System Summary
          </h2>
          <ul className="list-disc pl-6 text-sm space-y-2">
            <li>
              Total Rain Captured: <b>15,200 Liters</b>
            </li>
            <li>
              Tank Utilization: <b>78%</b> (Current month)
            </li>
            <li>
              Groundwater Recharge: <b>12,000 Liters</b>
            </li>
          </ul>
        </section>

        {/* Section 2: Cost Analysis */}
        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3 border-b border-[#d1d5dc] pb-2">
            💰 Cost Analysis
          </h2>
          <table className="w-full text-sm border border-[#d1d5dc]">
            <thead>
              <tr className="bg-[#f3f4f6]">
                <th className="border p-2">Item</th>
                <th className="border p-2">Estimated Cost</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border p-2">Installation</td>
                <td className="border p-2">₹ 1,20,000</td>
              </tr>
              <tr>
                <td className="border p-2">Annual Maintenance</td>
                <td className="border p-2">₹ 5,000</td>
              </tr>
              <tr>
                <td className="border p-2">Expected Lifespan</td>
                <td className="border p-2">15+ Years</td>
              </tr>
            </tbody>
          </table>
        </section>

        {/* Section 3: Savings Estimation */}
        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3 border-b border-[#d1d5dc] pb-2">
            💡 Savings Estimation
          </h2>
          <ul className="list-disc pl-6 text-sm space-y-2">
            <li>
              Annual Water Bill Savings: <b>₹ 25,000</b>
            </li>
            <li>
              Payback Period: <b>4.5 Years</b>
            </li>
            <li>
              ROI (10 Years): <b>3.2x</b>
            </li>
            <li>
              Subsidy Eligible: <b>Yes (Up to 30%)</b>
            </li>
          </ul>
        </section>

        {/* Section 4: Seasonal Predictions */}
        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3 border-b border-[#f3f4f6] pb-2">
            🌦 Seasonal Predictions
          </h2>
          <p className="text-sm mb-2">
            Based on local rainfall trends, expected water capture:
          </p>
          <table className="w-full text-sm border border-[#f3f4f6]">
            <thead>
              <tr className="bg-[#f3f4f6]">
                <th className="border p-2">Season</th>
                <th className="border p-2">Estimated Capture</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border p-2">Summer</td>
                <td className="border p-2">3,000 Liters</td>
              </tr>
              <tr>
                <td className="border p-2">Monsoon</td>
                <td className="border p-2">20,000 Liters</td>
              </tr>
              <tr>
                <td className="border p-2">Winter</td>
                <td className="border p-2">5,000 Liters</td>
              </tr>
            </tbody>
          </table>
        </section>

        {/* Section 5: Key Benefits */}
        <section>
          <h2 className="text-xl font-semibold mb-3 border-b border-[#f3f4f6] pb-2">
            🌱 Key Benefits
          </h2>
          <ul className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm">
            <li className="bg-[#f3f4f6] p-3 rounded">
              Save up to 40% on water bills
            </li>
            <li className="bg-[#f3f4f6] p-3 rounded">
              Recharge groundwater naturally
            </li>
            <li className="bg-[#f3f4f6] p-3 rounded">
              Eligible for govt subsidies
            </li>
            <li className="bg-[#f3f4f6] p-3 rounded">
              Eco-friendly & drought resilient
            </li>
          </ul>
        </section>
      </div>

      {/* Download Button */}
      <div className="text-center mt-6">
        <button 
        onClick={handleClick}
        className="bg-[#155dfc] text-[#fff] px-6 py-3 rounded-lg shadow-md hover:bg-[#1447e6] cursor-pointer">
          📥 Download PDF
        </button>
      </div>
    </div>
  );
};

export default PDFReport;
